### ISSUE TITLE
陳忠建 website is no longer available 

### ISSUE THREAD

**Issue by Ro66ieyu** [songquanpeng/ZiGAN-crawler#1]
陳建忠website is no longer accessible. Do you have a back up of the 隶書 (including 鄧石如）？
Thanks

**Comment by songquanpeng** [comment]
No, I no longer engage in research activities

**Comment by FKClose9** [comment]
> 陳建忠website is no longer accessible. Do you have a back up of the 隶書 (including 鄧石如）？ Thanks

Hello. May I ask if you have solved this problem or if there are any alternative solutions？
